version: 2

models:
  - name: dim_location
    columns:
      - name: location_id
        tests: [not_null, unique]

  - name: dim_property
    columns:
      - name: property_id
        tests: [not_null, unique]

  - name: fact_listings
    columns:
      - name: listing_id
        tests: [not_null, unique]

      - name: location_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_location')
              field: location_id

      - name: property_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_property')
              field: property_id